# Based on https://github.com/Microsoft/GSL/blob/master/.travis.yml

language: cpp
compiler: g++

before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq

sudo: false

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/deps/cmake

install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p "${DEPS_DIR}" && cd "${DEPS_DIR}"
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"

  ############################################################################
  # Install a recent CMake (unless already installed on OS X)
  ############################################################################
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      if [[ -z "$(ls -A ${DEPS_DIR}/cmake/bin)" ]]; then
        CMAKE_URL="https://cmake.org/files/v3.8/cmake-3.8.1-Linux-x86_64.tar.gz"
        mkdir -p cmake && travis_retry wget --no-check-certificate --quiet -O - "${CMAKE_URL}" | tar --strip-components=1 -xz -C cmake
      fi
      export PATH="${DEPS_DIR}/cmake/bin:${PATH}"
    else
      if ! brew ls --version cmake &>/dev/null; then brew install cmake; fi
    fi

before_script:
  - cd "${TRAVIS_BUILD_DIR}"
  - cmake . -Bbuild
  - cmake --build build -- -j2

script:
  - cd build
  - ctest --output-on-failure -j2

notifications:
  email: false